// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJxdFje218mzFvgpnujp0SVvIMPDpTiM',
    appId: '1:630156070486:web:53abb02f51da2bab9275f7',
    messagingSenderId: '630156070486',
    projectId: 'b1-cba79',
    authDomain: 'b1-cba79.firebaseapp.com',
    storageBucket: 'b1-cba79.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBs3u2lt8A6MLktAHZsgWJxfdMBRbm7E',
    appId: '1:630156070486:android:5637d1aac9a972799275f7',
    messagingSenderId: '630156070486',
    projectId: 'b1-cba79',
    storageBucket: 'b1-cba79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAO2K5NPDmuy46Uf32D-3DChc4P2mMVtY',
    appId: '1:630156070486:ios:8c5e5f1e618c23ce9275f7',
    messagingSenderId: '630156070486',
    projectId: 'b1-cba79',
    storageBucket: 'b1-cba79.firebasestorage.app',
    iosBundleId: 'com.example.firebseAuth',
  );
}
